AVIASALES_API_BASE_URL = 'http://api.travelpayouts.com'

AVIASALES_API_AIRPORTS_URL = AVIASALES_API_BASE_URL + '/data/en/airports.json'
AVIASALES_API_CITIES_URL = AVIASALES_API_BASE_URL + '/data/en/cities.json'
AVIASALES_API_COUNTRIES_URL = AVIASALES_API_BASE_URL + '/data/countries.json'
AVIASALES_API_PRICES_URL = AVIASALES_API_BASE_URL + '/v1/prices/cheap'
