"""added cities and airports tables

Revision ID: 1417b58eaeae
Revises: 772bf8dfc463
Create Date: 2020-04-11 16:20:19.993959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1417b58eaeae'
down_revision = '772bf8dfc463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('flightable', sa.Boolean(), nullable=False),
    sa.Column('codes_combo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_airports_codes_combo'), 'airports', ['codes_combo'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('codes_combo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_cities_codes_combo'), 'cities', ['codes_combo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_codes_combo'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_airports_codes_combo'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
