"""foreign_key_cities_contries

Revision ID: 28fae1858ace
Revises: 5a4c1c88c099
Create Date: 2020-04-30 20:20:13.595113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fae1858ace'
down_revision = '5a4c1c88c099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cities', 'countries', ['country_code'], ['country_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='foreignkey')
    # ### end Alembic commands ###
