"""foreign_key_cities_contries

Revision ID: 28fae1858ace
Revises: 5a4c1c88c099
Create Date: 2020-04-30 20:20:13.595113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fae1858ace'
down_revision = '5a4c1c88c099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities") as b_op:
        b_op.create_foreign_key("fk_cities_country_code_countries", 'cities', ['country_code'], ['country_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities") as b_op:
        b_op.drop_constraint("fk_cities_country_code_countries", type_='foreignkey')
    # ### end Alembic commands ###
