"""new column in event

Revision ID: 5206a457a0dd
Revises: d04a0ef996da
Create Date: 2020-05-01 22:22:38.029416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5206a457a0dd'
down_revision = 'd04a0ef996da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event") as b_op:
        b_op.create_foreign_key("fk_event_artist_id_artists", 'artists', ['artist_id'], ['artist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event") as b_op:
        b_op.drop_constraint("fk_event_artist_id_artists", type_='foreignkey')
    # ### end Alembic commands ###
