"""new column in event

Revision ID: 5206a457a0dd
Revises: d04a0ef996da
Create Date: 2020-05-01 22:22:38.029416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5206a457a0dd'
down_revision = 'd04a0ef996da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'artists', ['artist_id'], ['artist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'artist_id')
    # ### end Alembic commands ###
