"""countries table, cities table multilanguage fields

Revision ID: 5a4c1c88c099
Revises: b7c485918526
Create Date: 2020-04-29 22:59:58.544903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4c1c88c099'
down_revision = 'b7c485918526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('es_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('fr_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('it_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('ru_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'ru_name')
    op.drop_column('cities', 'it_name')
    op.drop_column('cities', 'fr_name')
    op.drop_column('cities', 'es_name')
    # ### end Alembic commands ###
