"""new tables: airlines, tickets, new moderated fields for cities and countries

Revision ID: 6ce216ad98f8
Revises: 9deb48daf229
Create Date: 2020-05-02 04:53:35.262756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce216ad98f8'
down_revision = '9deb48daf229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('airline_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('airline_code', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('return_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cities', sa.Column('moderated_name1', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('moderated_name2', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('moderated_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'moderated_name')
    op.drop_column('cities', 'moderated_name2')
    op.drop_column('cities', 'moderated_name1')
    op.drop_table('tickets')
    op.drop_table('airlines')
    # ### end Alembic commands ###
