"""country_table, country_code_unique, foreign_keys

Revision ID: 91bb2fad7b58
Revises: 5a4c1c88c099
Create Date: 2020-05-01 18:58:45.480738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bb2fad7b58'
down_revision = '5a4c1c88c099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code')
    )
    op.add_column('cities', sa.Column('de_name', sa.String(), nullable=True))
    with op.batch_alter_table("cities") as b_op:
        b_op.create_foreign_key("fk_cities_country_code_countries", 'cities', ['country_code'], ['country_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities") as b_op:
        b_op.drop_constraint("fk_cities_country_code_countries", type_='foreignkey')
    op.drop_column('cities', 'de_name')
    op.drop_table('countries')
    # ### end Alembic commands ###
