"""countries, cities (foreign_key) in one migration

Revision ID: b4239834d575
Revises: 5206a457a0dd
Create Date: 2020-05-02 00:37:57.217796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4239834d575'
down_revision = '5206a457a0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code')
    )
    op.add_column('cities', sa.Column('de_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('es_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('fr_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('it_name', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('ru_name', sa.String(), nullable=True))
    with op.batch_alter_table("cities") as b_op:
        b_op.create_foreign_key("fk_cities_country_code_countries", 'cities', ['country_code'], ['country_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities") as b_op:
        b_op.drop_constraint("fk_cities_country_code_countries", type_='foreignkey')
    op.drop_column('cities', 'ru_name')
    op.drop_column('cities', 'it_name')
    op.drop_column('cities', 'fr_name')
    op.drop_column('cities', 'es_name')
    op.drop_column('cities', 'de_name')
    op.drop_table('countries')
    # ### end Alembic commands ###
