
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities") as b_op:
        b_op.create_foreign_key("fk_cities_country_code_countries", 'cities', ['country_code'], ['country_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities") as b_op:
        b_op.drop_constraint("fk_cities_country_code_countries", type_='foreignkey')
    # ### end Alembic commands ###
    
